# Parameters config

ext:
conda_prefix: 


# --- checkm --- #
checkm2_db: 
checkm1_db: 

# --- gunc --- #
diamond_db: 

# --- gtdbtk --- #

gtdb_db: '/workdir/lam4003/Databases/GTDBTk_R202_010123'


# --- quast --- #
min_contig_len: 100
