#'''Parameters config.'''#


ext: '/home/lam4003/bin/camp_mag-qc/workflow/ext'


# --- checkm --- #

checkm2_db: '/workdir/lam4003/Databases/CheckM2_05232023/uniref100.KO.1.dmnd'
checkm1_db: '/workdir/lam4003/Databases/CheckM_2015_01_16_010123'


# --- gunc --- #

diamond_db: '/workdir/lam4003/Databases/GUNC_10072023/gunc_db_progenomes2.1.dmnd'


# --- gtdbtk --- #

gtdb_db: '/workdir/lam4003/Databases/GTDBTk_R202_010123'

# --- cmseq --- #

minqual:    30
mincov:     10
dominant_frq_thrsh:     0.8


# --- quast --- #

min_contig_len:   100
