#'''Parameters config.'''#


ext: ''

# --- checkm --- #

checkm2_db: ''
checkm1_db: ''


# --- gunc --- #

diamond_db: ''


# --- gtdbtk --- #

gtdb_db: ''


# --- cmseq --- #

minqual:    30
mincov:     10
dominant_frq_thrsh:     0.8


# --- quast --- #

min_contig_len:   2500