#'''Command-line usage resource config.'''#


# --- checkm --- #

checkm_threads: 20
checkm_mem_mb: 50000


# --- gunc --- #

gunc_threads: 20
gunc_mem_mb: 50000


# --- gtdbtk --- #

gtdbtk_threads: 20
gtdbtk_mem_mb: 50000


# --- mapsort --- #

mapsort_threads: 20
mapsort_mem_mb: 50000


# --- quast --- #

quast_threads: 20
quast_mem_mb: 50000


# --- prokka --- #

prokka_threads: 20
prokka_mem_mb: 50000
